openapi: 3.0.1
info:
  title: Upcoming Movies API
  description: "This is the API docs for Upcoming Movies project"
  version: 1.0.0
servers:
  - url: https://localhost:3000/api

tags:
  - name: Upcoming movies
paths:
  /movie/upcoming:
    get:
      tags:
        - Upcoming movies
      summary: Retrieve an object with the results array formatted
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
          example: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MoviesList"

        500:
          description: Internal Server Error
  /movie/:id:
    get:
      tags:
        - Upcoming movies
      summary: Retrieve details of a movie
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
          example: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieDetails"

        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: invalid movie id

        500:
          description: Internal Server Error

components:
  schemas:
    MovieDetails:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        genres:
          type: string
        overview:
          type: string
        poster_path:
          type: string
        backdrop_path:
          type: string
        release_date:
          type: string
        tagline:
          type: string
        popularity:
          type: integer
        vote_count:
          type: integer
        vote_average:
          type: integer
        production_countries:
          type: string

    MoviesList:
      type: object
      properties:
        total_pages:
          type: number
        results:
          type: array
          items:
            $ref: "#/components/schemas/Movie"

    Movie:
      type: object
      properties:
        id:
          type: integer
        poster_path:
          type: string
        backdrop_path:
          type: string
        genres:
          type: string
        title:
          type: string
        release_date:
          type: string
        overview:
          type: string
